---
name: idr0124-esteban-heartmorphogenesis/experimentA
version: 1

defaults:
  # Should the column be processed when creating bulk-annotations (yes/no)
  include: false
  # Columns type of the bulk-annotations column
  type: string

  # If non-empty a string used to separate multiple fields in a column
  # White space will be stripped
  split:
  # Should this column be included in the clients (yes/no)
  includeclient: true
  # Should this column be visible in the clients, if no the column should be
  # hidden in the client but will still be indexed by the searcher (yes/no)
  visible: true
  # Should empty values be omitted from the client display
  omitempty: true

columns:

  - name: Characteristics [Organism Part]
    clientname: Organism Part
    include: true

  - name: Characteristics [Strain]
    clientname: Strain
    include: true

  - name: Experimental Condition [Genotype]
    clientname: Genotype
    include: true

  - name: Characteristics [Developmental Stage]
    clientname: Developmental Stage
    include: true

  - name: Experimental Condition [Embryo Collection]
    clientname: Embryo Collection
    include: true

  - name: Assay Name
    include: true

  - name: Comment [Image File Comments]
    clientname: Image File Comments
    include: true


  ######################################################################
  # mapr groups
  ######################################################################

  - group:
      namespace: openmicroscopy.org/mapr/organism
      columns:
        - name: Characteristics [Organism]
          clientname: Organism
          include: true

  - group:
      namespace: openmicroscopy.org/mapr/phenotype
      columns:
      - name: Phenotype
        clientname: Phenotype
        include: yes
      - name: Phenotype Term Name
        clientname: Phenotype Term Name
        include: yes
      - name: Phenotype Term Accession
        clientname: Phenotype Term Accession
        include: yes
      - name: Phenotype Term Accession URL
        clientname: Phenotype Term Accession URL
        include: yes


advanced:
  ignore_missing_primary_key: true
  primary_group_keys:
    - namespace: openmicroscopy.org/mapr/organism
      keys:
        - Organism
    - namespace: openmicroscopy.org/mapr/phenotype
      keys:
      - Phenotype
